### ISSUE TITLE
Use consistent formatting for the CSS code.

### ISSUE THREAD

**Issue by josephtkim** [djdavve/prj-rev-bwfs-dasmoto#5]
As with the HTML code, always stay consistent with the formatting in any language you use. Here is how you might format the CSS code

```css
/* CSS Document */
h1 {
  text-align: center;
  font-size: 100px;
  font-weight: bold;
  color: khaki;
  background-image: url(https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg);
}

body { 
  font-family: helvetica;
}

h3 {
  font-size: 320px;
  font-weight: bold;
  text-color: white;
}

h3 .brushes {
  background-color: lightcoral; 
}

h3 .frames { 
  font-size: 100px;
}

h3 .paint {
  background-color: blue;
}

.strong {
  color:blue; 
}
```
