### ISSUE TITLE
Simplify CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [djdavve/prj-rev-bwfs-dasmoto#6]
It is a good idea to try and simplify the CSS code to make the code cleaner and to remove repetitive code. You did a great job doing this for the font-family property, but you can simplify further for the font-weight property. 

```css
h1, h3 {
  font-weight: bold;
}
```
