### ISSUE TITLE
Some syntax errors in the CSS code

### ISSUE THREAD

**Issue by josephtkim** [djdavve/prj-rev-bwfs-dasmoto#7]
https://github.com/djdavve/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/css/style.css#L16

Instead of text-color, use color,

```css
color: white;
```

https://github.com/djdavve/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/css/style.css#L19-L21

When applying the selector for a tag with a specific class, you would need to write it as one, like

```css
h3.brushes {
  background-color: lightcoral; 
}
h3.frames { 
  font-size: 100px;
}
h3.paint {
  background-color: blue;
}
```
